version: "3"
services:
  psbo_group3:
    build: .
    restart: always
    ports:
      - 80:8080
    links:
      - mongo_db:psbo_group3db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
